export const config = {
  cargo: "Data Scientist  |  Machine Learning Engineer  |  AI Enthusiast",
  bio: {
    es: "Profesional de datos full-stack con dominio de todo el ciclo de vida de IA/ML — desde el análisis exploratorio y desarrollo de modelos hasta la orquestación de ingeniería de datos, arquitectura cloud escalable y construcción de plataformas de datos para analítica avanzada e IA. Más de 6 años de experiencia en riesgo financiero, econometría, NLP, pronósticos y soluciones cloud-native, con profunda expertise en Python, SQL, PySpark y el ecosistema Azure (Databricks, Data Factory, Azure ML). Sólida formación académica con Maestría en Economía e Ingeniería Financiera. Actualmente ampliando hacia IA Generativa y flujos agénticos: RAGs, LangChain y Prompt Engineering.",
    en: "Full-stack data professional skilled across the entire AI/ML lifecycle — from exploratory analysis and model development to data engineering orchestration, scalable cloud architecture, and building data platforms that serve advanced analytics and AI. Combines 6+ years of experience spanning financial risk, econometrics, NLP, forecasting, and cloud-native solutions, with deep expertise in Python, SQL, PySpark, and the Azure ecosystem (Databricks, Data Factory, Azure ML). Solid academic foundation including a Master's in Economics and Financial Engineering. Currently expanding into Generative AI and Agentic workflows: RAGs, LangChain, and Prompt Engineering.",
  },
  stack: [
    { label: "Python",     color: "py"  },
    { label: "SQL",        color: "sql" },
    { label: "Azure",      color: "az"  },
    { label: "FastAPI",    color: "py"  },
    { label: "Databricks", color: "db"  },
    { label: "GenAI",      color: "ai"  },
    { label: "PySpark",    color: "def" },
  ],
  proyectos: [
    {
      id: "P01",
      destacado: true,
      titulo: { es: "Simulador Financiero", en: "Financial Simulator" },
      estado: "live",
      desc: {
        es: "Amortización de crédito con tabla detallada y API FastAPI production-ready.",
        en: "Credit amortization with detailed table and production-ready FastAPI.",
      },
      stack: ["FastAPI", "Python", "Azure"],
      preview: null as string | null,
      demo: "https://aleossa.com/amortization",
      repo: "https://github.com/alejomd17/aleossa-api",
    },
    {
      id: "P01b",
      destacado: true,
      titulo: { es: "KPI Agent — MineSight", en: "KPI Agent — MineSight" },
      estado: "live",
      desc: {
        es: "Sistema end-to-end que automatiza extracción, consolidación y visualización de KPIs financieros desde informes trimestrales de minería (Mineros S.A.) usando Gemini API para parseo de PDFs en español.",
        en: "End-to-end system that automates extraction, consolidation, and visualization of financial KPIs from mining quarterly reports (Mineros S.A.) using Gemini API to parse Spanish-language PDFs.",
      },
      stack: ["Gemini API", "FastAPI", "React"],
      preview: "/previews/minesight.png" as string | null,
      demo: "https://aleossa.com/minesight",
      repo: "https://github.com/alejomd17/MineSightDD",
    },
    {
      id: "P03",
      destacado: true,
      titulo: { es: "Dynamic Pricing", en: "Dynamic Pricing" },
      estado: "live",
      desc: {
        es: "Motor de precios dinámicos con modelo ML y API REST para ajuste automático de tarifas en tiempo real.",
        en: "Dynamic pricing engine with ML model and REST API for automatic real-time rate adjustment.",
      },
      stack: ["Python", "FastAPI", "ML"],
      preview: "/previews/dynamic_pricing.png" as string | null,
      demo: "https://aleossa.com/dynamic_pricing",
      repo: "https://github.com/alejomd17/dynamic-pricing",
    },
    {
      id: "P05",
      destacado: true,
      titulo: { es: "Agoria — Real Estate Intel", en: "Agoria — Real Estate Intel" },
      estado: "live",
      desc: {
        es: "Plataforma PropTech con scraping, valoración ML y análisis agéntico del mercado inmobiliario colombiano.",
        en: "PropTech platform with scraping, ML valuation, and agentic analysis of Colombian real estate.",
      },
      stack: ["Scraping", "ML", "Next.js"],
      preview: "/previews/agoria.png" as string | null,
      demo: "https://agoria.properties",
      repo: "https://github.com/alejomd17/agoria-web",
    },
    {
      id: "P02",
      destacado: false,
      titulo: { es: "Plataforma Energética Evolti", en: "Evolti Energy Platform" },
      estado: "wip",
      desc: {
        es: "Forecasting de precios energéticos y newsletter automático para el sector energético colombiano.",
        en: "Energy price forecasting and automated newsletter for the Colombian energy sector.",
      },
      stack: ["Prophet", "LangGraph", "Azure"],
      preview: null as string | null,
      demo: null as string | null,
      repo: null as string | null,
    },
  ],
  contacto: {
    email: "alejo-mdm@hotmail.com",
    phone: "+57 312 2396942",
    whatsapp: "https://wa.me/573122396942",
    linkedin: "https://linkedin.com/in/alejomd17",
    github: "https://github.com/alejomd17",
    hdv_es: "/pdfs/HdV_AMD.pdf",
    cv_en: "/pdfs/CV_AMD.pdf",
  },
};

export const badgeColors: Record<string, string> = {
  py:  "bg-[#0f2a1a] text-[#5DCAA5]",
  az:  "bg-[#0a1e30] text-[#85B7EB]",
  ai:  "bg-[#1e1030] text-[#AFA9EC]",
  db:  "bg-[#0d1e30] text-[#378ADD]",
  sql: "bg-[#1a1a0a] text-[#EF9F27]",
  def: "bg-[#1a2a2a] text-[#a8c8d8]",
};
